### ISSUE TITLE
KeyExpired() function should use the *key* creation time, not the *sig*

### ISSUE THREAD

**Issue by paulfurley** [ProtonMail/crypto#10]
Hello!

I see you've made some mods to [`KeyExpired`](https://github.com/ProtonMail/crypto/blob/master/openpgp/packet/signature.go) - cool!

It seems you've still got the same issue as golang/crypto though, that expiry should be calculated from the key creation time, not the signature creation time:

https://github.com/golang/go/issues/22312

**Comment by twiss** [comment]
Fixed by https://github.com/ProtonMail/crypto/commit/31f8b485a409a514a7645d5f9ca39c1bf02613cb :)
