### ISSUE TITLE
Feature request for iOS local storage encryption

### ISSUE THREAD

**Issue by abjurato** [ProtonMail/crypto#11]
In order to replace [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) library in iOS project so far I'll need following methods:
1. `encryptSymmetrically(data: Data, with key: Data) -> Data`
2. `decryptSymmetrically(data: Data, with key: Data) -> Data`
3. `deriveStrongPassphrase(from pin: String, salt: Data, iterations: Int) -> Data`

First two are used in accessors of AuthCredential, UserInfo and mailboxPassord, etc so they'll be called frequently and have to be as fast as possible. For symmetrical encryption I've been using AES with ECB block mode, with 32 byte keys.
The third one is used every time user unlocks the app with PIN, and i've found out that PBKDF2 of CryptoSwift with sha256 was _disturbingly_ slow  with more than 2000 iterations on iPhone 5S so I'd prefer to have opportunity to vary this number for different devices.

But actually cryptography is none of my fields of expertise so please feel free to change implementation details as you think would be better

**Comment by abjurato** [comment]
1. `- (ModelsSessionSplit*)getSessionFromSymmetricPacket:(NSData*)keyPackage password:(NSString*)password error:(NSError**)error;`

2. `- (NSData*)symmetricKeyPacketWithPassword:(ModelsSessionSplit*)sessionSplit password:(NSString*)password error:(NSError**)error;`

3. `- (NSData*)symmetricKeyPacketWithPassword:(ModelsSessionSplit*)sessionSplit password:(NSString*)password error:(NSError**)error;`

**Comment by twiss** [comment]
Fixed by https://gitlab.protontech.ch/ProtonMail/go-pm-crypto/merge_requests/4.
