### ISSUE TITLE
Use of internal package internal/syscall/unix not allowed, on OpenBSD

### ISSUE THREAD

**Issue by icyphox** [ProtonMail/crypto#49]
Hi, I'm trying to build a package relying on this lib on OpenBSD. I get:

```
../../go/pkg/mod/github.com/!proton!mail/crypto@v1.0.1-0.20191122234321-e77a1f03baa0/rand/rand_openbsd.go:8:2: use of internal package internal/syscall/unix not allowed
```
 
What can be done here?

**Comment by twiss** [comment]
Hey :wave: Probably this:
https://github.com/ProtonMail/crypto/blob/1fa7f403fb9c3aa7b47443e1e3b39c80d6eedcb6/rand/rand_openbsd.go#L8
should be replaced with
```go
	"golang.org/x/crypto/internal/syscall/unix"
```
I don't know how easy it would be for you to test this. Probably the package you're building has a `replace` statement in its go.mod file to use this package - you could modify it to point to a local directory, and then clone this library there and modify it per the above. If you can, let me know if that works.
Alternatively, I can just commit the above, I'm pretty sure that should fix it.

**Comment by icyphox** [comment]
Ah, I see.

> Alternatively, I can just commit the above, I'm pretty sure that should fix it.

Yes, please. I think it'd be better having the fix upstream. :)

**Comment by twiss** [comment]
Done: 71bec3603bf3a9bb42e31198bc4ab49985570971.

Although I can't test the build, I've confirmed that at least `GOOS=openbsd go build ./...` succeeds, now :)

**Comment by icyphox** [comment]
Thank you! :)
